### ISSUE TITLE
webpack live reload when base file changes

### ISSUE THREAD

**Issue by andreyvolokitin** [posthtml/posthtml-extend#11]
There is no recompiling and no live reload of a page when base file contents changes

**Comment by andreyvolokitin** [comment]
I got this working. Is it really as simple as adding the following before [this line](https://github.com/posthtml/posthtml-extend/blob/master/lib/extend.es6#L44)? 
```js
tree.messages.push({
          type: 'dependency',
          file: layoutPath,
          from: tree.options.from
        });
```
(for details see [```posthtml``` api](https://github.com/posthtml/posthtml/blob/7ff3f9b3c4aef5c7f25ed4cd0b07d15ee44544f0/lib/api.js#L87) and ```posthtml-loader``` [usage](https://github.com/posthtml/posthtml-loader/blob/master/lib/index.js#L117) of it).

But [again](https://github.com/posthtml/posthtml/issues/254#issuecomment-354613832), it stops working (no recompile) if I also have ```posthtml-beautify``` declared in my ```posthtml.config.js``` (cc @michael-ciniawsky)

**Comment by Scrum** [comment]
@andreyvolokitin close ?
