### ISSUE TITLE
Configurable tag names

### ISSUE THREAD

**Issue by giuseppeg** [posthtml/posthtml-extend#22]
Hi there thank you for making this plugin - it works great!

Would you consider making the tag names configurable via options? For example I'd like to use `template`, `slot` and `fill` as such:

```html
<!-- base.html -->
<slot name="title"></slot>
<slot name="content"></slot>

<!-- about.html -->
<template src="base.html">
  <fill name="title">About</fill>
  <fill name="content">howdy</fill>
</template>
```

I think the only thing to keep in mind is that to make sure that the `extend` tag has a `src` attribute

**Comment by giuseppeg** [comment]
I implemented this in a local branch and I was wondering if there is a reason why the `block` removals is not done at L51 https://github.com/posthtml/posthtml-extend/blob/a625469ba7546cc1f682a925341469060cacb1df/lib/extend.es6#L44-L51 rather than L22? 

```js
const blockNodes = getBlockNodes(extendsNode)
// ...
```

**Comment by Scrum** [comment]
@giuseppeg 
> I implemented this in a local branch and I was wondering if there is a reason why the `block` removals is not done at L51

Not quite sure what exactly is going wrong?

**Comment by giuseppeg** [comment]
@Scrum nothing important. Thank you for adding this feature 🖤 The change I suggested in that comment would allow nested `<extends>`.

Since I wasn't sure you were going to accept my feature requests I ended up forking this plugin (will open source it in the future) and added the following features:

* nested `extends`
* renamed the `extends` tag to `template` which the plugin handles only when it has the `src` attribute (to not conflict with the standard HTML one)
* unnamed `slot` like in the HTML spec
* use `slot/fill` tag names

**Comment by Scrum** [comment]
> Since I wasn't sure you were going to accept my feature requests I ended up forking this plugin (will open source it in the future) and added the following features:
> 
>     * nested `extends`
> 
>     * renamed the `extends` tag to `template` which the plugin handles only when it has the `src` attribute (to not conflict with the standard HTML one)
> 
>     * unnamed `slot` like in the HTML spec
> 
>     * use `slot/fill` tag names

Sounds very cool, feel free to be PR.

I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository as `owner` and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by giuseppeg** [comment]
Thanks for the offer I will ping you once I publish my library so that you can take a look and we can decide if it makes sense to add it to the posthtml org
