### ISSUE TITLE
Join us at PostHTML Org :)

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/posthtml-extend#5]

**Comment by maltsev** [comment]
Thank you for the inviting, Michael!

Do you expect some contribution from me? Unfortunately, I've little spare time yet. So I won't be active for the time being. If it's okay for you I'd be glad to join.

**Comment by michael-ciniawsky** [comment]
Hi, 

> Do you expect some contribution from me? 

Nope nothing particular. It's open source at free time for must of us i guess. Contribute or participate when you find time and mood to do :)

> Unfortunately, I've little spare time yet. 

yep, thats why i emphasize some community effort with a 'core plugin' ecosystem and shared responsibilities e.g keep deps up-to-date, fix small bugs, answers questions related to plugins and/or newcomers in general etc etc. I'm currently given a small amount of work time to shape some edges related to posthtml and posthtml organistation related things (unified README style, documentation, start editor syntax highlighters (imports, modules, extends, appends, inject, sugarml syntax blub blub...)

Would it be ok from your side to either
- Transfer your posthtml work to posthtml org*1) and led me update/add the README CONTRIBUTING, .github templates 

1)
- npm publish stays by the original author, 
- bigger code changes (if any) must be reviewed/approved by the maintainer as well, 
- clear note in the README who made the plugin [See](https://)https://github.com/posthtml/sugarml#maintainer) 
- and the upcoming posthtml website (soon i promise :)) will list all organisation members and there work.

I'm asking directly for transfer, because in my opinion your plugins and the catalog are nessecities for a solid org core (extend, inline-css, css-modules...)

-plugins-catalog {align the catalog with the website project somehow either as subdomain or style  related, directly in the org may improve notice of existance :))
-htmlnano (if someone looks at the org to get a overview of posthtml for usage decision making and sees candy like this it would improve the 'first look' significantly :)
- If you want to keep your work or some work directly at your github portfolio (understandable). Accept a PR with README updates or if in a rush provide push access to the repos. Don't feel pushed to do anything if you don't want it's no requirement or something like that :), as long as you agree with some basic org standards join us please
  
  ?

**Comment by maltsev** [comment]
That's a great idea! I'll definitely contribute to it. Next weekend I'll have more time, so we can handle that.

**Comment by michael-ciniawsky** [comment]
kk estonia as your github profile suggests is your current location and timezone? if just notify my here when you have a few free minutes, it's only a hour ahead  :)

**Comment by maltsev** [comment]
Actually, I'm abroad yet. But I still have the same timezone (UTC+3).

**Comment by michael-ciniawsky** [comment]
kk

``` js
if (vacation) {
 'Enjoy'
} else {
 'Hang in there'
}
```

:)

Take your time, ready when you are

**Comment by maltsev** [comment]
```
Uncaught ReferenceError: vacation is not defined
```

Anyway, thanks :-)

**Comment by michael-ciniawsky** [comment]
😄

**Comment by maltsev** [comment]
Okay, your proposal sounds good to me. I'm ready to transfer all related repositories to the posthtml namespace. Just let me know when you'll be ready, @michael-ciniawsky @awinogradov.
If you need any help let me also know. I could contribute a few hours on a weekend for that.

**Comment by michael-ciniawsky** [comment]
@maltsev cool :+1: sry for the delay :),  @awinogradov @voischev etc. currently setting up org related things (code style, README's, MAINTAINERS).At the moment i don't exaclty know whats coming up. i notify you when this is settled and you can first take a look if you agree on that?

**Comment by maltsev** [comment]
Sure.

**Comment by michael-ciniawsky** [comment]
hi 👋 invite should be send. guidlines are @https://github.com/posthtml/posthtml/blob/master/docs/index.md and the repo style is @https://github.com/posthtml/posthtml-plugin-boilerplate. i can take care of the style updates if you haven't the time rigth now 👍

**Comment by maltsev** [comment]
I accepted the invite, thanks @awinogradov!

@michael-ciniawsky it'd very nice if you take care of the styles. Should I wait for your PR first or can I already transfer my repositories to the posthtml namespace?

**Comment by michael-ciniawsky** [comment]
when you have time to spare move them :) , many others need to by updated aswell

**Comment by maltsev** [comment]
Unfortunately, I cannot transfer the repositories, the error `You don’t have admin rights to posthtml` appears. @awinogradov can you give me those rights?

**Comment by awinogradov** [comment]
@maltsev try it now;)

**Comment by awinogradov** [comment]
🔥
