### ISSUE TITLE
Handle Configurable Parser

### ISSUE THREAD

**Issue by jescalan** [posthtml/posthtml-extend#6]
So it's possible now to change the default html parser, which means that this plugin doesn't work correctly if the parser was changed, as it uses the`posthtml-parser` directly. IMHO, the right way to handle this is to have posthtml expose its options to plugins, which means you could pull `options.parser` from posthtml and use this to parse layouts.

However, this feature is not a part of posthtml yet. I do have a fork where the feature has been implemented though, will update if it's merged and PR a fix. Just wanted to put this here so people are aware!

**Comment by Scrum** [comment]
@jescalan status this issue ?

**Comment by jescalan** [comment]
Made a PR for this years ago, it wasn't accepted, and it's a feature of reshape. I'm not sure if someone has implemented it for posthtml yet!

**Comment by Scrum** [comment]
this is about https://github.com/posthtml/posthtml/issues/242 ?

**Comment by jescalan** [comment]
I'm not sure to be honest, that is a link to a random issue that I don't understand. What it was originally about is explained clearly in the body of the issue. I think at this point we should probably close it and move on.
