### ISSUE TITLE
[docs]: Transfer to PostHTML organization

### ISSUE THREAD

**Issue by maltsev** [posthtml/posthtml-extend#7]
- [x] Transfer repository to PostHTML organization.
- [x] Update repository links (`package.json`, `README.md`).
- [x] Add changelog (#4).
- [x] Update `README.md`.

**Comment by Scrum** [comment]
@maltsev maybe now ?

**Comment by maltsev** [comment]
Not sure why _Update `README.md`_ hasn't been checked. I think the transfer was already completed and we can close the issue. Let me know if I miss something.
